config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  resources :about, only: [:index]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  http_basic_authenticate_with :name => ENV["USERNAME"], :password => ENV["PASSWORD"]

  def show
    @statistics = {
      product_count: get_product_count,
      category_count: get_category_count
    }
  end

  private

  def get_product_count
    Product.count()
  end

  def get_category_count
    Category.count()
  end
end

app/views/admin/dashboard/show.html.erb
<section>
  <header class="page-header">
      <h1>Admin &raquo; Dashboard</h1>
  </header>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Statistics</th>
        <th scope="col">Count</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row"><%= link_to 'Products', admin_products_path  %></th>
        <td><%= @statistics[:product_count]%></td>
      </tr>
      <tr>
        <th scope="row"><%= link_to 'Categories', admin_categories_path  %></th>
        <td><%= @statistics[:category_count]%></td>
      </tr>
    </tbody>
  </table>
</section>